import React from 'react';
import { Link } from 'react-router-dom';
import { Wand2, FileText, Target, Crown } from 'lucide-react';

const features = [
  { icon: <Target size={24} />, title: 'JD Analysis Agent', desc: 'Paste any job description and our AI extracts critical ATS keywords ranked by importance.' },
  { icon: <Wand2 size={24} />, title: 'AI Bullet Rewriter', desc: 'Rewrites your experience bullets to naturally include target keywords and boost your ATS score.' },
  { icon: <FileText size={24} />, title: 'Pixel-Perfect PDF', desc: 'Download a professionally formatted, print-ready PDF generated by headless Chrome.' },
  { icon: <Crown size={24} />, title: 'Cover Letter Generator', desc: 'Pro users get AI-generated cover letters tailored to each specific job application.' },
];

export default function LandingPage() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-indigo-50 via-white to-purple-50">
      <nav className="flex items-center justify-between px-8 py-5">
        <h1 className="text-xl font-bold text-indigo-700">CareerForge Pro</h1>
        <div className="flex gap-4">
          <Link to="/login" className="text-sm text-gray-600 hover:text-indigo-600 font-medium">Sign In</Link>
          <Link to="/register" className="bg-indigo-600 text-white text-sm px-5 py-2 rounded-full hover:bg-indigo-700 font-medium">Get Started Free</Link>
        </div>
      </nav>

      <section className="text-center px-6 py-20 max-w-3xl mx-auto">
        <span className="bg-indigo-100 text-indigo-700 text-xs font-bold px-4 py-1.5 rounded-full tracking-wide uppercase">AI-Powered Resume Builder</span>
        <h2 className="text-5xl font-extrabold text-gray-900 mt-5 mb-4 leading-tight">
          Get Past the ATS.<br />Land More Interviews.
        </h2>
        <p className="text-gray-500 text-lg mb-8">
          CareerForge Pro uses AI to optimize your resume for any job description, boosting your ATS score and rewriting bullets that get noticed.
        </p>
        <div className="flex gap-4 justify-center">
          <Link to="/register" className="bg-indigo-600 text-white px-8 py-3 rounded-xl font-bold hover:bg-indigo-700 text-base">
            Build My Resume Free
          </Link>
          <Link to="/pricing" className="border-2 border-indigo-200 text-indigo-600 px-8 py-3 rounded-xl font-bold hover:bg-indigo-50 text-base">
            View Pricing
          </Link>
        </div>
      </section>

      <section className="max-w-4xl mx-auto px-6 py-12 grid grid-cols-1 md:grid-cols-2 gap-6">
        {features.map((f) => (
          <div key={f.title} className="bg-white rounded-2xl p-6 shadow-sm border hover:shadow-md transition">
            <div className="text-indigo-600 mb-3">{f.icon}</div>
            <h3 className="font-bold text-gray-800 mb-1">{f.title}</h3>
            <p className="text-sm text-gray-500">{f.desc}</p>
          </div>
        ))}
      </section>

      <footer className="text-center text-sm text-gray-400 py-8">
        © 2025 CareerForge Pro · Zaalima Development
      </footer>
    </div>
  );
}
